<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\**" />
    <EmbeddedResource Remove="Images\**" />
    <None Remove="Images\**" />
    <Page Remove="Images\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="calculator.ico" />
    <None Remove="calculator_icon-icons.com_72046.png" />
    <None Remove="close.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="calculator.ico" />
    <Resource Include="calculator_icon-icons.com_72046.png" />
  </ItemGroup>

</Project>
